INSERT INTO classificacao_ocorrencia (id, descricao) VALUES
(1,'Acidentes e traumas'),
(2,'Emergências médicas'),
(3,'Emergências policiais'),
(4,'Resgates/Desastres naturais'),
(5,'Risco imediato à vida'),
(6,'Outros');

INSERT INTO tipo_ocorrencia (id, descricao, id_classificacao_ocorrencia) VALUES
(1,'Agressão/Violência',1),
(2,'Ferimento por arma branca/arma de fogo',1),
(3,'Mordida de animal',1),
(4,'Picada de animais peçonhentos',1),
(5,'Quedas',1),
(6,'AVC/Derrame',2),
(7,'Alergia/Reação medicamentosa',2),
(8,'Convulsões/Epilepsia',2),
(9,'Psiquiátricos/Tentativa de suicídio',2),
(10,'Dor abdominal',2),
(11,'Dor de cabeça',2),
(12,'Dor nas costas',2),
(13,'Dor no peito/Problemas cardíacos',2),
(14,'Envenenamento/Overdose',2),
(15,'Gravidez/Parto/Aborto',2),
(16,'Problemas respiratórios',2),
(17,'Furto/Roubo/Assalto',3),
(18,'Homicídio',3),
(19,'Lesão corporal',3),
(20,'Tentativa de homicídio',3),
(21,'Violência doméstica',3),
(22,'Violência sexual/Estupro',3),
(24,'Alagamento/Enchente/Enxurrada',4),
(25,'Soterramento/Deslizamento',4),
(26,'Incêndio em edificação',4),
(27,'Incêndio florestal/Entulhos',4),
(28,'Incêndio veicular',4),
(29,'Incidente com aeronave',4),
(30,'Pessoa desaparecida/perdida',4),
(31,'Produtos perigosos',4),
(32,'Resgates de animais',4),
(33,'Salvamento em altura',4),
(34,'Afogamentos e acidentes de mergulho',5),
(35,'Choque elétrico',5),
(36,'Desmaio/mal súbito',5),
(37,'Obstrução de vias aéreas',5),
(38,'Parada cardiorespiratória',5),
(39,'Acidente de trânsito',1),
(40,'Outros',6);

