INSERT INTO classificacao_ocorrencia (id, descricao) VALUES
(1,'Acidentes e traumas'),
(2,'Emergências médicas'),
(3,'Emergências policiais'),
(4,'Resgates/Desastres naturais'),
(5,'Risco imediato à vida'),
(6,'Outros');

INSERT INTO tipo_ocorrencia (id, descricao, id_classificacao_ocorrencia, id_instituicao_orgao) VALUES
(1,'Agressão/Violência',1,1),
(2,'Ferimento por arma branca/arma de fogo',1,1),
(3,'Mordida de animal',1,1),
(4,'Picada de animais peçonhentos',1,1),
(5,'Quedas',1,1),
(6,'AVC/Derrame',2,3),
(7,'Alergia/Reação medicamentosa',2,3),
(8,'Convulsões/Epilepsia',2,3),
(9,'Psiquiátricos/Tentativa de suicídio',2,3),
(10,'Dor abdominal',2,3),
(11,'Dor de cabeça',2,3),
(12,'Dor nas costas',2,3),
(13,'Dor no peito/Problemas cardíacos',2,3),
(14,'Envenenamento/Overdose',2,3),
(15,'Gravidez/Parto/Aborto',2,3),
(16,'Problemas respiratórios',2,3),
(17,'Furto/Roubo/Assalto',3,2),
(18,'Homicídio',3,2),
(19,'Lesão corporal',3,2),
(20,'Tentativa de homicídio',3,2),
(21,'Violência doméstica',3,2),
(22,'Violência sexual/Estupro',3,2),
(24,'Alagamento/Enchente/Enxurrada',4,1),
(25,'Soterramento/Deslizamento',4,1),
(26,'Incêndio em edificação',4,1),
(27,'Incêndio florestal/Entulhos',4,1),
(28,'Incêndio veicular',4,1),
(29,'Incidente com aeronave',4,1),
(30,'Pessoa desaparecida/perdida',4,1),
(31,'Produtos perigosos',4,1),
(32,'Resgates de animais',4,1),
(33,'Salvamento em altura',4,1),
(34,'Afogamentos e acidentes de mergulho',5,1),
(35,'Choque elétrico',5,1),
(36,'Desmaio/mal súbito',5,1),
(37,'Obstrução de vias aéreas',5,1),
(38,'Parada cardiorespiratória',5,1),
(39,'Acidente de trânsito',1,1),
(40,'Outros',6,1);